name: deploy
on:
  push:
    branches:
      - 'master'
      - 'release/**'
    paths:
      - 'serverless.yml'
      - 'stock-report.js'
      - 'helpers/**'
      - 'layer/**'
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install lambda dependencies
      run: npm i
    - name: Install layer dependencies
      run: |
        cd layer/nodejs
        npm i
    - name: serverless-check
      uses: kaskadi/action-slscli@master
      with:
        command: 'deploy --noDeploy'
        should_throw: true
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_KEY_SECRET }}
        ES_ID: ${{ secrets.ES_ID }}
        ES_SECRET: ${{ secrets.ES_SECRET }}
        ES_ENDPOINT: ${{ secrets.ES_ENDPOINT }}
    - name: serverless-deploy
      uses: kaskadi/action-slscli@master
      with:
        command: 'deploy -v'
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_KEY_SECRET }}
        ES_ID: ${{ secrets.ES_ID }}
        ES_SECRET: ${{ secrets.ES_SECRET }}
        ES_ENDPOINT: ${{ secrets.ES_ENDPOINT }}
